### ISSUE TITLE
Switch from 'host of the certain group' scheme to variable defined solution

### ISSUE THREAD

**Issue by bissquit** [cloud-labs-infra/ansible-etcd-cluster-certificates#13]
**Is your feature request related to a problem? Please describe.**
Switch from 'host of the certain group' scheme to variable defined solution

**Describe the solution you'd like**
Now we have the following scheme:
```yaml
delegate_to: "{{ groups[etcd_cert_default_inventory_group_name][0] }}"
```
Lest choose appropriate host using some variable like:
```yaml
etcd_cert_init_ca_node: false
```
and extra task that set required fact for the other hosts in the play like the following (got as example from other role):
```yaml
- name: Set hostname of initial master for other nodes
  ansible.builtin.set_fact:
    k8s_cluster_init_main_node_hostname: "{{ inventory_hostname }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ ansible_play_hosts }}"
```

**Describe alternatives you've considered**
Alternative is already used but it's not convenient way because we have to set group name and restricted by the first node of that group

**Additional context**
Not applicable
