### ISSUE TITLE
Add possibility to generate server/peer/client cert based on condition

### ISSUE THREAD

**Issue by bissquit** [cloud-labs-infra/ansible-etcd-cluster-certificates#6]
Example:

```yaml
# defaults/main.yml
etcd_cert_generate_server: true

# tasks/main.yml
- name: Generate client-to-server (server) certificates
  ansible.builtin.include_tasks:
    file: generate-server.yml
  when: etcd_cert_generate_server | bool == true
```
